import { Inter, Anton } from "next/font/google";

import "./globals.css";
import Footer from "./components/footer";
import ClientLayoutWrapper from "./components/client-layout-wrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cities Project Gloabl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${anton.variable} antialiased`}
      >
        <ClientLayoutWrapper>
          {children}
        </ClientLayoutWrapper>
        <Footer />
      </body>
    </html>
  );
}
